version: 8.1-fpm-alpine
services: 
    main:
        build: 
            context: .
            dockerfile: Dockerfile
        command: 'php artisan serve --host=0.0.0.0'
        volumes:
            - .:/app
        ports:
            - 8000:8000